<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GameManagedPath Condition="'$(GameManagedPath)' == ''">../../.scratch/managed</GameManagedPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.4.11" />
    <PackageReference Include="HarmonyX" Version="2.10.2" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all" />
    <Reference Include="RoR2"><HintPath>$(GameManagedPath)/RoR2.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameManagedPath)/UnityEngine.CoreModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(GameManagedPath)/UnityEngine.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="com.unity.multiplayer-hlapi.Runtime"><HintPath>$(GameManagedPath)/com.unity.multiplayer-hlapi.Runtime.dll</HintPath><Private>False</Private></Reference>
  </ItemGroup>
</Project>
